import Link from "next/link";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white px-6 py-12">
      <div className="max-w-2xl mx-auto">
        <Link href="/">
          <Button variant="ghost" size="sm" className="gap-2 mb-8 -ml-2">
            <ArrowLeft className="w-4 h-4" />
            Back
          </Button>
        </Link>

        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-8">Last updated: April 2026</p>

        <div className="prose prose-gray max-w-none space-y-6 text-gray-700 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">1. Acceptance of terms</h2>
            <p>
              By accessing or using NestGenie (the &ldquo;Service&rdquo;), you agree to be bound by
              these Terms of Service. If you do not agree, do not use the Service.
              These terms apply to all users, including parents and guardians who interact
              with NestGenie via SMS or the web companion.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">2. Description of service</h2>
            <p>
              NestGenie is an AI-powered family assistant delivered primarily via SMS.
              It provides daily briefings, coordinates outbound messages to third-party
              contacts on your behalf (with your explicit approval), and offers
              parenting guidance personalized to your stated philosophy. The web companion
              provides account management, family profile setup, and audit history.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">3. Eligibility</h2>
            <p>
              You must be at least 18 years old and a registered user (your phone number
              must be provisioned by an authorized NestGenie administrator) to use the
              Service. NestGenie is intended for use by parents and legal guardians only.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">4. Not medical advice</h2>
            <p>
              NestGenie is not a medical service. Nothing generated by NestGenie constitutes
              medical advice, diagnosis, or treatment. Always consult a qualified healthcare
              professional — including your pediatrician — for any medical question or concern.
              NestGenie will always direct you to consult your pediatrician for health-related matters.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">5. Not a mental health service</h2>
            <p>
              NestGenie is not a mental health service and does not provide mental health
              counseling, therapy, diagnosis, or crisis intervention. If you are experiencing
              a mental health emergency, please contact a qualified professional or call 988
              (Suicide & Crisis Lifeline).
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">6. Outbound messages and TCPA</h2>
            <p>
              NestGenie may draft messages to third-party contacts (such as caregivers,
              pediatricians, or schools) on your behalf. You must review and explicitly
              approve every such message before it is sent. You are responsible for
              ensuring that contacts have consented to receive SMS messages via NestGenie.
              NestGenie requires you to record TCPA consent for each contact.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">7. Acceptable use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 text-sm">
              <li>Use NestGenie to harass, threaten, or deceive any person</li>
              <li>Send unauthorized commercial messages through the outbound flow</li>
              <li>Attempt to reverse-engineer, scrape, or tamper with the Service</li>
              <li>Provide false information about consents or permissions</li>
              <li>Use NestGenie for any unlawful purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">8. AI-generated content</h2>
            <p>
              NestGenie uses large language models (AWS Bedrock) to generate briefings,
              guidance, and outbound drafts. AI-generated content may be inaccurate,
              incomplete, or inappropriate for your specific situation. You are solely
              responsible for reviewing and acting on AI-generated content. Do not rely
              on NestGenie output for legal, medical, financial, or safety-critical decisions
              without independent verification.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">9. Data and privacy</h2>
            <p>
              Your use of NestGenie is also governed by our{" "}
              <Link href="/privacy" className="text-[#2E7D32] underline">
                Privacy Policy
              </Link>
              . By using the Service, you consent to data collection and processing as
              described therein.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">10. Termination</h2>
            <p>
              We may suspend or terminate your access to NestGenie at any time, with or
              without notice, if you violate these Terms or for any other reason at our
              discretion. You may delete your account at any time from Settings → Privacy & Data.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">11. Disclaimer of warranties</h2>
            <p>
              The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any
              kind, express or implied, including accuracy, reliability, or fitness for a
              particular purpose. We do not warrant that the Service will be uninterrupted
              or error-free.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">12. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, NestGenie and its operators shall not
              be liable for any indirect, incidental, consequential, or punitive damages
              arising from your use of the Service, including any reliance on AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">13. Changes to terms</h2>
            <p>
              We may update these Terms at any time. We will notify you of material changes
              via SMS or email. Continued use of the Service after changes constitutes
              acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-900 mb-2">14. Contact</h2>
            <p>
              For questions about these Terms, email{" "}
              <a href="mailto:legal@nestgenie.com" className="text-[#2E7D32] underline">
                legal@nestgenie.com
              </a>
              .
            </p>
          </section>

          <div className="pt-4 flex gap-4 text-sm">
            <Link href="/privacy" className="text-[#2E7D32] underline">Privacy Policy</Link>
            <Link href="/sms-terms" className="text-[#2E7D32] underline">SMS Terms</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
